<a href="https://colab.research.google.com/github/omotoshoahmad/Tensorflowing/blob/main/DL_with_Tensorflow003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Changing the Data type of tensors

In [ ]:
import tensorflow as tf

In [ ]:
# create a new tensor with default datatype (float32)
B = tf.constant  ([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
# create a new tensor with default datatype (int32)
C = tf.constant  ([7, 10])
C.dtype

tf.int32

In [ ]:
# change the bit precision from 32 to 16
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

F = tf.cast(C, dtype=tf.float16)
F, F.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

###  Aggregating tensors
Aggregating sensors is coombining them by carrying various operations on either a single tensor or a combination of tensors.

In [ ]:
# get the absolute values of a tensor
D = tf.constant([-7, -10])
D

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

More aggregation on tensors


*   Maximum value in a sensor
*   Minimum value in a tensor
* Mean values of a tensors
* median values of a tensor




In [ ]:
import numpy as np
# create a random tensor 
E = tf.constant(np.random.randint(0, 100, size=50))

tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# find the minimum
print(tf.reduce_min(E))

# find the max
tf.reduce_max(E)

tf.Tensor(0, shape=(), dtype=int64)


<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [ ]:
# find the mean
tf.reduce_mean (E)

print(E)

tf.Tensor(
[23 16 66  6 14 37 29 64 53 74  0 60 61 78 27  3 10 52  8 85 51 70 67 17
 29 50 28 66 96 59 22 72 76  3 43 86 67 76 81 52 67 74 30 65 60  6 51 66
 32  6], shape=(50,), dtype=int64)


In [ ]:
# ?find the variance and standard deviation
E = tf.cast(E, dtype=tf.float32)
print(tf.math.reduce_variance(E))

# find the standard deviation
print(tf.math.reduce_std(E))

tf.Tensor(713.5376, shape=(), dtype=float32)
tf.Tensor(26.712124, shape=(), dtype=float32)


We can also use the teensorflow probability module to find the variance

In [ ]:
import tensorflow_probability as tfp
print(tfp.stats.variance(E))

tf.Tensor(713.5376, shape=(), dtype=float32)


## Finding positional Maximum and Minimum

The essence of this, is to make a decision on your output tensor. Most times the NN returns an output tensor containing rows of predict probability, the positional max refers to the column with the highest probability in a row and positional minimum refers to the column with the lowest probability in a row.


In [ ]:
#  create a dummy tensor
tf.random.set_seed(42)

F = tf.random.uniform (shape = [50])

In [ ]:
# Find positional maximum
p_max = tf.argmax(F)

F[p_max]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# The maximum value of F can also be found using reduce_max
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Finding the positional minimum
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### 🧰 Create two tensors of different dimensions and find the positional max and minimum.

### Squeezing a tensor - removing all single dimension

In [ ]:
# create a new tensor
E = tf.random.uniform (shape = [1, 1, 1, 1, 50])

In [ ]:
tf.squeeze (E)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

One-hot encoding

In [ ]:
# encoding categorical data is an important step in preparing data for the model.
tf.one_hot([0, 1, 2, 3], depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

Each column represents the indicies fed into the function, whenever an index is represnted by "1" , the rest is represented by "0". That means the row represents the object read

### More mathematical operations

In [ ]:
# Square 
H = tf.range(1, 10)

In [ ]:
tf.square (tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([ 1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float32)>

In [ ]:
# sqaure root
tf.sqrt (tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# logarithms
tf.math.log ( tf.cast(H, dtype=tf.float32)
)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Neural Network Regression.
