<a href="https://colab.research.google.com/github/omotoshoahmad/Tensorflowing/blob/main/DL_with_Tensorflow001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started - Turning Data into Sensors

## Introduction to tensors

In [3]:
#import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [4]:
# Create tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
  #  check the dimension
  scalar.ndim

0

In [8]:
# create a vector
vector = tf.constant([10,7])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [9]:
# check the dimension
vector.ndim

1

In [12]:
# create a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [14]:
# check the dimension
matrix.ndim

2

In [18]:
# create another matrix
another_matrix = tf.constant([[10., 7.,],
                              [7., 10.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [20]:
# check the dimension
another_matrix.ndim


2

In [22]:
# create a tensor 
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                      [10, 11, 12]],
                      [[13, 14, 15],
                      [16, 17, 18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [23]:
# check the dimension
tensor.ndim

3

Notes:
1. **Scalar** = A 0-dimensional array which can be any single number
2. **Vecor** = A 1-dimensional array which represents magnitude and direction.
3. **Matrix** = A 2-dimensional array of numbers
4. **Tensor** = An n-dimensional array of numbers (where n can be any number)