<a href="https://colab.research.google.com/github/omotoshoahmad/Tensorflowing/blob/main/DL_with_Tensorflow002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Indexing Tensors

Tensors can be indexed just like python lists

In [8]:
import tensorflow as tf

In [9]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [10]:
rank_4_tensor[:2, :2, :2, :2]
# get the firdt 2 elements from each dimension

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [11]:
# get the first element from each dimension except for the last one
rank_4_tensor[:1,:1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [12]:
# create a rank 2 sensor
# rank_2__sensor = tf.zeros(shape=[2,2])

rank_2_sensor = tf.constant([[10,7],
                             [3,4]],)

# get the last item of our dimensions
rank_2_sensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [13]:
# Add an extra dimension to the rank 2 tensor
rank_3_tensor = rank_2_sensor[..., tf.newaxis]
rank_3_tensor

# we can also add to the front
rank_3_tensor = rank_2_sensor[tf.newaxis, ...]
rank_3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [14]:
# Expanding the axis using tf.expand_dims
tf.expand_dims(rank_2_sensor, axis=0) # expands the first axis 


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [15]:
tf.expand_dims(rank_2_sensor, axis=1) # expands the middle or second axis 

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [16]:
tf.expand_dims(rank_2_sensor, axis=-1) # expands the last axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating tensors (Tensor operations)

**Basic Operations**

In [17]:
# Addition operator
tensor = tf.constant([[10, 7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [18]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [19]:
# multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [20]:
# Substraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [21]:
# using the tensor built-in-function
tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In [22]:
# matrix multiplication in tensorflow
tf.linalg.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [23]:
# using python standard oprator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [24]:
tensor.shape

TensorShape([2, 2])

In [25]:
# create a 3 by 2 tensor.
X = tf.constant([[2, 3, 4],
                 [5,6,7]])

Y = tf.constant ([[7, 8, 9],
                  [10, 11, 12]])

In [26]:
X.shape

TensorShape([2, 3])

In [27]:
# find the dot product of the matrices. We have to reshape the matrices such the column of first m,atrix is equal to the row of the second matrix
X @ tf.reshape(Y, shape=(3, 2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 85,  94],
       [166, 184]], dtype=int32)>

In [30]:
# find the dot product of the matrices. We have to reshape the matrices such the column of first m,atrix is equal to the row of the second matrix
Y = tf.reshape(X, shape=(3, 2))

z = tf.matmul(X, Y)

In [31]:
# Transposing the matrix shifts its axis
X, tf.transpose(X)


(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 3, 4],
        [5, 6, 7]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 5],
        [3, 6],
        [4, 7]], dtype=int32)>)